### ISSUE TITLE
Tags & CriticMarkup Highlight Colours

### ISSUE THREAD

**Issue by mjknght** [pryley/styled-tags-for-foldingtext#2]
I appreciate you may not be updating this (excellent) plugin any longer, but on the off chance that you are: I occasionally use tags within inline blocks of CriticMarkup, and the standard tag style interrupts the highlight colour, which just doesn't look right. I have been messing about with it, with no luck – is there any easy way to rectify this in the LESS/styles? Any help appreciated enormously.

<img width="214" alt="screen shot 2016-02-19 at 17 21 48" src="https://cloud.githubusercontent.com/assets/9498434/13183133/49434f24-d72d-11e5-8ce2-3d37b31486fd.png">

**Comment by pryley** [comment]
Reply with an example block of text that I can paste into FoldingText to replicate and I will take a look.

**Comment by mjknght** [comment]
Hi Pryley. Thanks for your response! Here is an example:

`@tag1 is fine. {++But @tag2 within this comment is not quite right.++}`

**Comment by pryley** [comment]
v1.0.1 - tags are no longer styled inside critic markup
